### ISSUE TITLE
Cannot connect to device in order to get services 

### ISSUE THREAD

**Issue by bwomsm1** [rlangoy/bluepy_examples_nRF51822_mbed#4]
I am trying to connect to the device as following: 
```
        p = Peripheral(dev.addr, ADDR_TYPE_RANDOM)

        services = p.getServices()

        # displays all services
        for service in services:
            print(service)
```

I can confirm that `dev.addr` provides a proper mac address of BLE device, 

But I am getting the following error:
```
Traceback (most recent call last):
  File "/home/pi/pycharm-community-2022.2.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pi/pycharm-community-2022.2.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pi/workspace/test-python/test2.py", line 21, in <module>
    p = Peripheral(dev.addr, ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 48:27:ea:b1:10:6d, addr type: random
```

What am I doing wrong?

**Comment by rlangoy** [comment]
I am sorry but you code looks ok 
Did you try running the code as root (sudo).

Does connecting to the device work with gatttool ?
sudo gatttool -t random -b  48:27:ea:b1:10:6d -I

**Comment by bwomsm1** [comment]
Thanks @rlangoy for your response, 
Yes I am running as root user with `sudo`.

I was able to pass this line correctly: 
`sudo gatttool -t random -b 48:27:ea:b1:10:6d -I`

Then when I got the device CMD tool, I sent this command:
`connect`
and got after a while this message: 
`Error: connect to 48:27:EA:B1:10:6D: Connection refused (111)`

I am quite new in this world of BLE, does this means that I cannot perform the connect either from the Python code? 
Maybe my target BLE device (samsung S8 device) is not a connectable device? 

Thanks

**Comment by rlangoy** [comment]
I am not familiar with using BLE servers on a Samsung S8. Another easy way is to install NRF Connect (app for Android &iOS) and create an Advertiser that allows BLE connections

**Comment by bwomsm1** [comment]
@rlangoy I installed the android `NRF connect` mobile app,
Defined my advertising as follow:
![Screenshot_20230316-083417_nRF Connect](https://user-images.githubusercontent.com/5571230/225534526-00df5819-96e5-43d6-9aef-d3852eff4d9e.jpg)

**I was able to discover the device** 
But when I tried to perform `connect` as following:
```
peripheral = Peripheral()
peripheral.connect(dev.addr, dev.addrType)
```
I got an error:
`Failed to connect to peripheral 48:27:ea:b1:10:6d, addr type: public`



Some more log info about the ble message from the NRF app:
```
evice 48:27:ea:b1:10:6d (public), RSSI=-58 dB
(1, 'Flags', '1a')
(9, 'Complete Local Name', 'samsung_01')
(22, '16b Service Data', '0f1810')
----
samsung_01
----
address: 48:27:ea:b1:10:6d
addressType: public
connectable: True
```

**Comment by rlangoy** [comment]
If you run the commenad :  **sudo hciconfig hci0 lestates**  it could resolve if the Bluetooth Adapter does supoort Low-Energy.
This is the result from my linux-box :)
Supported link layer states:
        YES Non-connectable Advertising State
        YES Scannable Advertising State
        YES Connectable Advertising State
        YES Directed Advertising State
        YES Passive Scanning State
        YES Active Scanning State
        YES Initiating State/Connection State in Central Role
        YES Connection State in the Peripheral Role
        YES Non-connectable Advertising State and Passive Scanning State combination
        YES Scannable Advertising State and Passive Scanning State combination
        YES Connectable Advertising State and Passive Scanning State combination
        YES Directed Advertising State and Passive Scanning State combination
        YES Non-connectable Advertising State and Active Scanning State combination
        YES Scannable Advertising State and Active Scanning State combination
        YES Connectable Advertising State and Active Scanning State combination
        YES Directed Advertising State and Active Scanning State combination
        YES Non-connectable Advertising State and Initiating State combination
        YES Scannable Advertising State and Initiating State combination
        YES Non-connectable Advertising State and Central Role combination
        YES Scannable Advertising State and Central Role combination
        YES Non-connectable Advertising State and Peripheral Role combination
        YES Scannable Advertising State and Peripheral Role combination
        YES Passive Scanning State and Initiating State combination
        YES Active Scanning State and Initiating State combination
        YES Passive Scanning State and Central Role combination
        YES Active Scanning State and Central Role combination
        YES Passive Scanning State and Peripheral Role combination
        YES Active Scanning State and Peripheral Role combination
        YES Initiating State and Central Role combination/Central Role and Central Role combination

**Comment by bwomsm1** [comment]
Here is the output on my side: 
```
Supported link layer states:
	YES Non-connectable Advertising State
	YES Scannable Advertising State
	YES Connectable Advertising State
	YES Directed Advertising State
	YES Passive Scanning State
	YES Active Scanning State
	YES Initiating State/Connection State in Master Role
	YES Connection State in the Slave Role
	YES Non-connectable Advertising State and Passive Scanning State combination
	YES Scannable Advertising State and Passive Scanning State combination
	YES Connectable Advertising State and Passive Scanning State combination
	YES Directed Advertising State and Passive Scanning State combination
	YES Non-connectable Advertising State and Active Scanning State combination
	YES Scannable Advertising State and Active Scanning State combination
	YES Connectable Advertising State and Active Scanning State combination
	YES Directed Advertising State and Active Scanning State combination
	YES Non-connectable Advertising State and Initiating State combination
	YES Scannable Advertising State and Initiating State combination
	YES Non-connectable Advertising State and Master Role combination
	YES Scannable Advertising State and Master Role combination
	YES Non-connectable Advertising State and Slave Role combination
	YES Scannable Advertising State and Slave Role combination
	YES Passive Scanning State and Initiating State combination
	YES Active Scanning State and Initiating State combination
	YES Passive Scanning State and Master Role combination
	YES Active Scanning State and Master Role combination
	YES Passive Scanning State and Slave Role combination
	YES Active Scanning State and Slave Role combination
	YES Initiating State and Master Role combination/Master Role and Master Role combination
```

**Comment by bwomsm1** [comment]
> If you run the commenad : **sudo hciconfig hci0 lestates** it could resolve if the Bluetooth Adapter does supoort Low-Energy. This is the result from my linux-box :) Supported link layer states: YES Non-connectable Advertising State YES Scannable Advertising State YES Connectable Advertising State YES Directed Advertising State YES Passive Scanning State YES Active Scanning State YES Initiating State/Connection State in Central Role YES Connection State in the Peripheral Role YES Non-connectable Advertising State and Passive Scanning State combination YES Scannable Advertising State and Passive Scanning State combination YES Connectable Advertising State and Passive Scanning State combination YES Directed Advertising State and Passive Scanning State combination YES Non-connectable Advertising State and Active Scanning State combination YES Scannable Advertising State and Active Scanning State combination YES Connectable Advertising State and Active Scanning State combination YES Directed Advertising State and Active Scanning State combination YES Non-connectable Advertising State and Initiating State combination YES Scannable Advertising State and Initiating State combination YES Non-connectable Advertising State and Central Role combination YES Scannable Advertising State and Central Role combination YES Non-connectable Advertising State and Peripheral Role combination YES Scannable Advertising State and Peripheral Role combination YES Passive Scanning State and Initiating State combination YES Active Scanning State and Initiating State combination YES Passive Scanning State and Central Role combination YES Active Scanning State and Central Role combination YES Passive Scanning State and Peripheral Role combination YES Active Scanning State and Peripheral Role combination YES Initiating State and Central Role combination/Central Role and Central Role combination

I am running the code against Raspberry PI, which is actually Linux OS system :)

**Comment by rlangoy** [comment]
I am sorry but i realy does not know where the problem is located... :(  
The respone from you adapter does seem ok :)
Was the  **gatttool**  able to connect to the Phone while the "nRF Connect" app was advertiding ?
Maby the adafruit-circuitpython-ble (https://docs.circuitpython.org/projects/ble/en/latest/index.html) library  could work for you    ?

**Comment by bwomsm1** [comment]
Thanks for the help,
Yes, it was advertising from the android `nRF Connect` mobile app,

I will try `adafruit-circuitpython-ble`, let's see,
Can you recommend for more libraries? This is actually my second library which I am trying to work with, tried also `bluetooth`
